name: Build Hatari libretro core for iOS

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install cmake make git sdl2

      - name: Build iOS ARM64 libretro core
        env:
          PLATFORM: ios-arm64
        run: |
          make -f Makefile.libretro

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hatarib_libretro_ios
          path: |
            *.so
            *.dylib
